module.exports = {
  apps: [
    {
      name: 'local',
      script: './dist/main.js',
      exec_mode: 'cluster',
      instances: 2,
      watch: false,
      wait_ready: true,
      combine_logs: true,
      autorestart: true,
      max_memory_restart: '1G',
      node_args: '--max_old_space_size=1024',
      out_file: './logs/output.log',
      error_file: './logs/error.log',
      listen_timeout: 1000,
      kill_timeout: 1000,
    },
    {
      name: 'stdte-ts-server',
      script: './dist/main.js',
      exec_mode: 'cluster',
      instances: 2,
      watch: false,
      wait_ready: true,
      autorestart: true,
      max_memory_restart: '1G',
      node_args: '--max_old_space_size=1024',
      out_file: '/home/ubuntu/logs/output.log',
      error_file: '/home/ubuntu/logs/error.log',
      combine_logs: true,
      listen_timeout: 1000,
      kill_timeout: 1000,
    },
  ],
};
