### Signup
POST http://localhost:3000/credentials/signup
Content-Type: application/json

< ./signup.body.json

### Signin
POST http://localhost:3000/credentials/signin
Content-Type: application/json

< ./signin.body.json