name: Actions Test

on:
  push:
    branches:
      - actions

jobs:
  env:
    runs-on: ubuntu-22.04

    steps:
      - name: create .env
        run: |
          touch .env
          echo "$DEVELOP_ENVS" >> .env

      - name: upload .env
        uses: actions/upload-artifact@v3
        with:
          name: .env
          path: .env
