name: Deploy

on:
  push:
    branches:
      - master

    paths-ignore:
      - docs
      - test
      - README.md

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [20]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: import submodules
        run: npm run submodule

      - name: install packages
        run: npm run ci

      - name: build application
        run: npm run build
