name: Test

on:
  push:
    branches: ['master']
    paths-ignore: ['*.md', 'docs', '.github/workflows/envs.yaml']

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [20]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: install dependencies
        run: |
          npm ci
          npm run submodule

      - name: docker database
        run: |
          cd docker/database
          docker compose up --build -d
          cd sub_modules/entity
          npm ci
          npm run start:sync

      - name: init database
        run: |
          cd sub_modules/entity
          npm ci
          npm run start:sync

      - name: test application
        run: npm run test
