name: Test

on:
  push:
    branches:
      - master

    paths-ignore:
      - docs
      - README.md
      - .gitbub/workflows/envs.yaml

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [20]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: install package
        run: npm ci

      - name: pull submodules
        run: |
          npm run submodule

      - name: docker database
        run: |
          cd docker/database
          docker-compose up --build -d

      - name: sync database
        run: |
          rm sub_modules/entity/.env
          cp .env.test sub_modules/entity/.env
          cd sub_modules/entity
          npm ci
          npm run start:sync

      - name: test application
        run: npm run test
